<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>创建时间-开始</name>
   <tag></tag>
   <elementGuidId>f45d93b2-24a9-437c-bd86-43f4e4162d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;start_created_time&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/活动管理-闲时优惠</value>
      <webElementGuid>1f8d03fc-47b4-4efc-b1d6-557666e9be12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
