<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>所属商户搜索框</name>
   <tag></tag>
   <elementGuidId>8e5a1e48-b50b-4993-a823-2f21e22ce53c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;store_id&quot;]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/系统管理-角色管理</value>
      <webElementGuid>27975380-5ee6-4ab7-8b1b-6ad6a6b8bef2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
