<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>会员等级搜索框</name>
   <tag></tag>
   <elementGuidId>42201304-2c06-4465-a4e3-371ba26051b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;member_level&quot;]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/用户中心-用户列表</value>
      <webElementGuid>7a60069c-4866-48cf-9db4-dcf1f8c71140</webElementGuid>
   </webElementProperties>
</WebElementEntity>
