<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>保持登录</name>
   <tag></tag>
   <elementGuidId>44075ee7-1d1a-4348-9d66-23abb3d14745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/div[3]/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.layui-icon.layui-icon-ok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f425326d-76da-441a-977b-d58b41014dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layui-icon layui-icon-ok</value>
      <webElementGuid>30573747-a6f4-4844-bd96-e00697adfb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/div[@class=&quot;layui-form-item&quot;]/div[@class=&quot;layui-unselect layui-form-checkbox&quot;]/i[@class=&quot;layui-icon layui-icon-ok&quot;]</value>
      <webElementGuid>9a25ca04-a635-4f17-9027-f3ca9ffd51df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div/i</value>
      <webElementGuid>b88d8711-7787-48a4-9666-00d9e14f9b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>2305eccd-2412-4d11-a468-efed356569b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
