<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>时间-月份入口1st</name>
   <tag></tag>
   <elementGuidId>9f386ef9-c964-4711-ac3a-ff607ee768ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;上个月&quot;]+[role=&quot;button&quot;]+span</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/首页-门店数据</value>
      <webElementGuid>a669e067-1399-4e64-8962-5634347b8b6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
