<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>创建时间-开始</name>
   <tag></tag>
   <elementGuidId>e3572bb2-2a79-4037-886a-99fe8de57ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;start_created_time&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/活动管理-邀请有礼</value>
      <webElementGuid>0a4682b5-f691-4bb5-b309-11d32e32a8ff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
