<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>到店时间-开始</name>
   <tag></tag>
   <elementGuidId>941c5fed-a11c-4ea2-9b83-aa616781e0f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#start_arrival_time</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/订单中心-服务订单</value>
      <webElementGuid>cdb51d86-9fe4-4752-868c-ff8bb1454ac9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
