<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>订单渠道搜索框</name>
   <tag></tag>
   <elementGuidId>4ef935cf-57da-4294-94ad-ffab8c62df67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;channel&quot;]/input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/frames/主页面/订单中心-服务订单</value>
      <webElementGuid>e4d017ba-6c48-4e16-be31-97e958e75e3f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
